--- #YAML:1.0
name:               URI-Unredirect
version:            0.01
abstract:           Remove obvious redirects from a C<URI>
author:
    - gray <gray@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:   0
    URI:          0
    URI::Escape:  0
resources:
    repository:  http://github.com/gray/uri-unredirect
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
